### PR TITLE
TravisCI, Grape 0.14.0 compatibility, RSpec, etc.

### PR DESCRIPTION
**Pull request by dblock**
Enable Travis-CI first on this repo before merging.

Successful build in https://travis-ci.org/dblock/newrelic-grape/builds/95475842

### CODE REVIEW

**Comment by flyerhzm** [comment]
@dblock do you think it's still necessary to maintain this gem? newrelic had already officially support grape, https://docs.newrelic.com/docs/agents/ruby-agent/frameworks/grape-instrumentation

**Comment by dblock** [comment]
Oh yes! I forgot about this. Feel free to merge or not merge this change, but we should just have a big warning in README that says to just use NewRelic's official implementation, which is [better](https://github.com/newrelic/rpm/blob/master/lib/new_relic/agent/instrumentation/grape.rb).

**Comment by dblock** [comment]
The only "good" reason to continue supporting this is in the NewRelic docs:

_If you want to use New Relic's official (built-in) Grape instrumentation, remove the newrelic-grape gem. (The transaction names captured by New Relic's official Grape instrumentation contain more detail. For example, they include the API version even if you are using non-path-based versioning.) However, if you want to continue using the newrelic-grape instrumentation to preserve your existing transaction names, you may safely ignore this message._

**Comment by flyerhzm** [comment]
@dblock I have released a new version and added a big warning in REDME, thanks.

**Pull request merged**
